-- This file is intentionally empty. blink.cmp is fully configured in
-- lua/plugins/lsp.lua via its lazy spec opts = {...}.
--
-- The original attempt to configure blink.cmp here (via a separate
-- lspconfig loop) was abandoned because it conflicted with the per-server
-- setup in lua/plugins/lsp.lua and with vim.lsp.enable() in lua/config/lsp.lua.
-- Keeping the single source of truth in the lazy spec is cleaner.
